### ISSUE TITLE
VM: Should allow value to be set on CREATE/Call in API

### ISSUE THREAD

**Issue by orogvany** [semuxproject/semux-core#192] opened 2019-07-04 16:59 UTC
After looking a bit closer at eth spec, it's perfectly valid to send amount on create/call

We should update API to allow this.

It looks like there's a bug on CALL where if you supply an amount, it doesn't seem to execute the call, just does the transfer.  Will write unit test for this case.

**Comment by semuxgo** [comment] 2019-07-04 19:04
I think the issue is the `local` condition check below. It's `null` if no value is provided

https://github.com/semuxproject/semux-core/blob/0682972eb5c329ff3897fb61297bc3779c8f57f3/src/main/java/org/semux/api/v2/SemuxApiImpl.java#L768-L774

**Comment by orogvany** [comment] 2019-07-04 19:48
That could be part of the problem, but I am specifying local=false, and still get odd behavior.

I can run through my tests again.  My setup is as follows

Create a contract that just does a transfer of amount/to to transfer from the contract to who you choose.

Call the contract setting amount>0.
Expected: sends amount to contract, and call is run sending some amount to target.  

It will send amount to target if 0 is specified as amount on call, but will not if value is specified.

**Comment by orogvany** [comment] 2019-07-04 19:49
It could be that the internal transaction is not calling with internal=false

**Comment by semuxgo** [comment] 2019-07-04 21:09
Fixed in the `develop` branch

**Closed by semuxgo** 2019-07-04 21:09 UTC
Labels: VM
