### ISSUE TITLE
estimate-gas returns 0

### ISSUE THREAD

**Issue by dinc334** [semuxproject/semux-core#282] opened 2020-01-27 18:01 UTC
# 🐛 Bug

When address has pending tx, estimate-gas returns 0 instead of normal value.

## To reproduce

1. Call estimate-gas
2. Make any kind of tx - call/transfer/create
3. Try to call estimate-gas with same params as in 1.

**Comment by semuxgo** [comment] 2021-04-14 17:49
Duplicate of https://github.com/semuxproject/semux-core/issues/286

**Closed by semuxgo** 2021-04-14 17:49 UTC
Labels: bug
