### ISSUE TITLE
Validator signalling for VM activation even after it was activated

### ISSUE THREAD

**Issue by honeycrypto** [semuxproject/semux-core#111] opened 2018-11-22 14:10 UTC
https://testnet.semux.info/explorer/block/689176 

`semux_online` validator doesn't see that VM was already activated. It continue signalling for activation each block and ignores (doesn't include in blocks) any VM calls.

**Comment by orogvany** [comment] 2018-11-22 15:40
Looks like dupe of #106

**Comment by orogvany** [comment] 2018-11-30 17:45
Closing in favor of #106

**Closed by orogvany** 2018-11-30 17:45 UTC
